-- D1 schema for the Redhand waitlist.
-- Apply with:  wrangler d1 execute redhand --remote --file=schema.sql

CREATE TABLE IF NOT EXISTS waitlist (
  email         TEXT PRIMARY KEY,
  price_shown   INTEGER,          -- the price on screen at signup, in whole units
  currency      TEXT DEFAULT 'EUR',
  country       TEXT,             -- from CF-IPCountry: tells us the channel's reach
  referer       TEXT,             -- which page produced the intent
  created_at    TEXT NOT NULL,
  seen_again_at TEXT              -- set when an existing address submits again
);

CREATE INDEX IF NOT EXISTS waitlist_created ON waitlist (created_at);


-- Anonymous post-scan signal: S3 as a by-product of S4.
-- No email, no component names, no SBOM. Counts and two answers.
CREATE TABLE IF NOT EXISTS signal (
  id                 INTEGER PRIMARY KEY AUTOINCREMENT,
  makes              TEXT,      -- free text, what they build
  doing              TEXT,      -- one of a fixed option set
  components_checked INTEGER,
  sbom_format        TEXT,
  clock_running      INTEGER,
  urgent_review      INTEGER,
  monitor            INTEGER,
  unresolvable       INTEGER,
  country            TEXT,
  created_at         TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS signal_created ON signal (created_at);


-- Return tracking. The id is generated by the browser and lives in its own
-- localStorage; nothing here identifies a person. `scans` separates a
-- qualified activation from someone who only read the page.
CREATE TABLE IF NOT EXISTS visitor (
  id            TEXT PRIMARY KEY,   -- random, browser-generated
  first_seen    TEXT NOT NULL,
  last_seen     TEXT NOT NULL,
  visits        INTEGER DEFAULT 1,
  scans         INTEGER DEFAULT 0,
  price_bucket  TEXT,               -- 'a' or 'b', which price they were shown
  first_referer TEXT,               -- host only, never a full URL
  country       TEXT
);

CREATE INDEX IF NOT EXISTS visitor_first_seen ON visitor (first_seen);
CREATE INDEX IF NOT EXISTS visitor_scans ON visitor (scans);

-- Record which price each waitlist signup saw, so the A/B reads cleanly.
ALTER TABLE waitlist ADD COLUMN price_bucket TEXT;
ALTER TABLE waitlist ADD COLUMN visitor_id TEXT;
